name: "Build Introduzione al ML"

on:
  push:
    branches: 
      - main
    paths:
      - ./Introduzione\ al\ ML/*
  pull_request:
    branches:
      - main
    paths:
      - ./Introduzione\ al\ ML/*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build PDF
        uses: dante-ev/latex-action@latest
        with:
          root_file: ./Introduzione\ al\ ML/Introduzione\ al\ ML.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Introduzione\ al\ ML.pdf
          path: ./Introduzione\ al\ ML/Introduzione\ al\ ML.pdf
